# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8cf0cf82daf2ebdebcda1870311233e514027ca22dead2e60cebad6d9051561a26a0962cc714b365b0c80b9f1161b667dfb96733f81069073dcc812b0f900c6e

test:
  secret_key_base: ac34fb13604161fff2de8900a8f44e64d681f94f4e5c8e8154ee1acd6a33548cfb1837a441e35d96b759d1a2229ab679145b4d7ebd04351dad3ca5e11de87e05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
